apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swiggy-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: swiggy.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swiggy-app
                port:
                  number: 80
